# Generated by Django 5.2.17 on 2026-10-06 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridNode',
            fields=[
                ('node_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('node_type', models.CharField(choices=[('SUBSTATION', 'Primary Distribution Substation'), ('FEEDER', 'Feeder Pillar / Sectionalizer'), ('TRANSFORMER', 'Distribution Transformer (11kV / 415V)'), ('CONSUMER_TAP', 'Consumer Tap / Terminal Pole')], default='TRANSFORMER', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('nominal_voltage', models.FloatField(default=230.0, help_text='Nominal phase voltage (V)')),
                ('max_rated_current', models.FloatField(default=30.0, help_text='Maximum rated continuous current (A)')),
                ('current_voltage', models.FloatField(default=230.0)),
                ('current_current', models.FloatField(default=0.0)),
                ('frequency', models.FloatField(default=50.0)),
                ('local_status', models.BooleanField(default=True, help_text='Physical sensor status at this node (True=Energized, False=De-energized/Faulted)')),
                ('effective_status', models.BooleanField(default=True, help_text='Calculated Zip-Line status (Local Status AND Effective Parent Status)')),
                ('last_telemetry_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Immediate upstream node supplying electrical power', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='backend.gridnode')),
            ],
        ),
        migrations.CreateModel(
            name='FaultLog',
            fields=[
                ('fault_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fault_type', models.IntegerField(choices=[(0, 'Normal (Healthy)'), (1, 'Short Circuit (Line-to-Ground / Phase Fault)'), (2, 'Physical Cable Cut (Open Circuit)'), (3, 'Overload / High Impedance Thermal Fault')])),
                ('severity', models.CharField(choices=[('LOW', 'Low - Advisory Warning'), ('MEDIUM', 'Medium - Elevated Risk'), ('CRITICAL', 'Critical - Immediate Outage / Fire Risk')], default='CRITICAL', max_length=15)),
                ('ai_confidence', models.FloatField(help_text='Neural Network softmax probability (0.0 to 1.0)')),
                ('diagnosis_summary', models.TextField()),
                ('voltage_snapshot', models.FloatField()),
                ('current_snapshot', models.FloatField()),
                ('delta_v_snapshot', models.FloatField()),
                ('delta_i_snapshot', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_logs', to='backend.gridnode')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('delta_voltage', models.FloatField(default=0.0)),
                ('delta_current', models.FloatField(default=0.0)),
                ('frequency', models.FloatField(default=50.0)),
                ('power_factor', models.FloatField(default=0.95)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries', to='backend.gridnode')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'System Administrator'), ('OPERATOR', 'Grid Control Operator'), ('FIELD_ENGINEER', 'Field Repair Technician')], default='OPERATOR', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('assigned_substation', models.CharField(blank=True, help_text='Operating sector or zone', max_length=100)),
                ('is_2fa_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
