# Generated by Django 5.2.17 on 2026-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridnode',
            name='area_landmark',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='gridnode',
            name='esp32_device_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gridnode',
            name='outage_reason',
            field=models.TextField(blank=True, default='', help_text='Specific cause for power loss if de-energized'),
        ),
        migrations.AddField(
            model_name='gridnode',
            name='pincode',
            field=models.CharField(blank=True, default='600001', max_length=10),
        ),
        migrations.AddField(
            model_name='gridnode',
            name='power_units_kwh',
            field=models.FloatField(default=120.5, help_text='Total Energy Units Recorded (kWh)'),
        ),
        migrations.AddField(
            model_name='gridnode',
            name='service_connection_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gridnode',
            name='zone_name',
            field=models.CharField(blank=True, default='Chennai Zone', max_length=100),
        ),
        migrations.AlterField(
            model_name='gridnode',
            name='node_type',
            field=models.CharField(choices=[('SUBSTATION', 'Primary Distribution Substation (400kV/230kV/110kV)'), ('FEEDER', 'Feeder Pillar / Sectionalizer (33kV/11kV)'), ('TRANSFORMER', 'Distribution Transformer (11kV / 415V)'), ('CONSUMER_TAP', 'Distribution Service Post / Pole Tap'), ('HOME_METER', 'Domestic Home ESP32 Smart Meter Box (230V Single Phase)')], default='TRANSFORMER', max_length=20),
        ),
    ]
