# Generated by Django 5.2.17 on 2026-10-06 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_gridnode_area_landmark_gridnode_esp32_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_code', models.CharField(max_length=50)),
                ('area_name', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=10)),
                ('notification_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('main_problem', models.CharField(blank=True, default='', max_length=250)),
                ('maintenance_info', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneArea',
            fields=[
                ('zone_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=60)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.IntegerField(default=3000)),
                ('is_power_on', models.BooleanField(default=True, help_text='True if Current is ON, False if Current is OFF')),
                ('total_homes', models.IntegerField(default=1420)),
                ('main_problem_title', models.CharField(blank=True, default='', max_length=150)),
                ('main_problem_location', models.CharField(blank=True, default='', max_length=200)),
                ('main_problem_cause', models.TextField(blank=True, default='')),
                ('fault_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fault_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('maintenance_status', models.CharField(default='NORMAL', max_length=50)),
                ('maintenance_team', models.CharField(blank=True, default='', max_length=150)),
                ('maintenance_van', models.CharField(blank=True, default='', max_length=50)),
                ('maintenance_step', models.CharField(blank=True, default='', max_length=200)),
                ('maintenance_progress', models.IntegerField(default=0)),
                ('estimated_restoration_time', models.CharField(blank=True, default='', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
