# Generated by Django 5.2.17 on 2026-10-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_gridnotification_zonearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_power_on', models.BooleanField(default=True, help_text='District Main Transmission Feed (True=ON, False=OFF)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('total_consumers', models.IntegerField(default=125000)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityZone',
            fields=[
                ('zone_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_power_on', models.BooleanField(default=True, help_text='Zone Feeder Bus (True=ON, False=OFF)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='backend.district')),
            ],
        ),
        migrations.CreateModel(
            name='AreaSector',
            fields=[
                ('area_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('pincode', models.CharField(max_length=10)),
                ('is_power_on', models.BooleanField(default=True, help_text='Area Sub-feeder switch (True=ON, False=OFF)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.IntegerField(default=2500)),
                ('total_homes', models.IntegerField(default=1420)),
                ('main_problem_title', models.CharField(blank=True, default='', max_length=150)),
                ('main_problem_location', models.CharField(blank=True, default='', max_length=200)),
                ('main_problem_cause', models.TextField(blank=True, default='')),
                ('fault_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fault_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('maintenance_status', models.CharField(default='NORMAL', max_length=50)),
                ('maintenance_team', models.CharField(blank=True, default='', max_length=150)),
                ('maintenance_van', models.CharField(blank=True, default='', max_length=50)),
                ('maintenance_step', models.CharField(blank=True, default='', max_length=200)),
                ('maintenance_progress', models.IntegerField(default=0)),
                ('estimated_restoration_time', models.CharField(blank=True, default='', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='backend.electricityzone')),
            ],
        ),
    ]
